### ISSUE TITLE
`onFilteredProducts` в `Cart.js`

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [dimakrugly/onix#24]
Не розумію чому ти передав функцію в `onFilteredProducts` в `Card` а не вже відфільтрований масив. Зазвичай в таких ситуаціях краще передавати одразу дані, а не функцію яка буде їх повертати

**Comment by dimakrugly** [comment]
Пофіксив, дякую)
Якщо чесно, на радощах що все працює забув зробити рефактор)
