### ISSUE TITLE
PropTypes

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [dimakrugly/onix#38]
Якщо передаєте обʼєкт в компонент, потрібно описатив в PropTypes тільки ті поля які використовуються в цьому компоненті

```
export const Cart = ({ filteredProducts }) => {
  <CartList
    filteredProducts={filteredProducts}
  />
}

Cart.propTypes = {
  filteredProducts: PropTypes.arrayOf(PropTypes.shape({}))
}
```

Такого опису буде більш ніж достатньо

Але якщо якесь поле використовується в цьому компоненті, то його потрібно вказувати

Це не помилка, скрокіше спрощення щоб не писати зайвого

**Comment by dimakrugly** [comment]
Done
