### ISSUE TITLE
Оновлення стейту

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [dimakrugly/onix#43]
В функції `arrowHandler` краще теж використати функцію для оновлення стейту, так як ти дістаеш `cartData` з `this.state`, обробляєш йього і знову зберігаєшь в стейт

**Comment by DmitriiMelnikOnix** [comment]
А ось в `onCartSearchGetValue` функція не потрібна,
```
 this.setState(() => ({
    cartSearchValue: event.target.value,
  }))
```

Весь сенс функції в тому щоб з неї ж дістати значення, тоді все буде працювати як заплановано)

**Comment by dimakrugly** [comment]
Зроблено необхідні фікси
