### ISSUE TITLE
Дублювання key

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [dimakrugly/onix#55]
<img width="1650" alt="Знімок екрана 2023-04-19 о 21 06 26" src="https://user-images.githubusercontent.com/59687966/233175430-6c781233-b35b-49c5-802b-28712d16d144.png">

**Comment by dimakrugly** [comment]
Не зустрічав раніше цю помилку, дивно що ти натрапив. Тут швидше всього питання до беку, сервіс newsdata.io дав два однакові об'єкти в массиві новин. Нажаль сервіс не надає параметр id в массиві, з іншого боку, це не вирішить проблему, так як використання айді як ключ все одно буде дублюватися. 
Вирішив проблему наступним чином

key={item.title + item.index}

Використання індексу массива звісно не дуже хороша практика, тим не менш, на мою думку в конкретному кейсі такий спосіб має право на життя. Я сто відсотково знаю, що массив не буде змінюватися, тому реакту не треба буде переписувати всі ключі, а комбінація title та index завжди буде унікальною, навіть якщо бек буде дублювати itemи
