### ISSUE TITLE
changeLanguage

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [dimakrugly/onix#58]
```
import translate from '../../services/translate/TranslateService';

<button type="button" className="en" onClick={() => translate.changeLanguage('en')}>
  <img className="flag" src={en} alt="en" />
</button>
```

щоб не використовувати `translate` безпосередньо можна використати 
```
const { i18n } = useTranslation()

i18n.changeLanguage('en') 
```

Мені такий спосіб подобається трохи більше, але приймаються обадва

**Comment by dimakrugly** [comment]
Так у функціональному компоненті з"явиться додаткові об"єктні дужки та ```return```

**Comment by dimakrugly** [comment]
Але все ж таки переробив, умовно кажучи згідно з вимогами проекту)
