### ISSUE TITLE
useFormik

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [dimakrugly/onix#60]
Formik гарна штука, одобрюю, але нажаль він не оновлювався вже 2 роки, і щоб в якийсь момент не довелось його випилювати віддаю перевагу react-hook-form

<img width="364" alt="Знімок екрана 2023-05-05 о 12 07 06" src="https://user-images.githubusercontent.com/59687966/236430578-2cdee740-318d-4b79-a66c-ce09e05104fa.png">

**Comment by dimakrugly** [comment]
Done! Переробив на react-hook-form
