### ISSUE TITLE
useImperativeHandle

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [dimakrugly/onix#64]
```javascript
useImperativeHandle(ref, () => ({
  show,
  hide,
}))
```

`useImperativeHandle` - цікава штука і добре що розібрався з нею, часто використовується в деяких підходах. Але конкретно в цьому випадку думаю простіше керувати компонентою за допомогою пропса `isShow`. Це скоріше побажання, нехай залишається)

**Comment by dimakrugly** [comment]
Спочатку так і планував, але вирішив спробувати щось нове) попрацювати з рефами та ін)
