### ISSUE TITLE
husky

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [dimakrugly/onix#7]
![image](https://user-images.githubusercontent.com/59687966/218340462-fcad8322-30a1-4780-8889-52985f913158.png)

Але потрібно ще до нього хуки для запуску 
https://github.com/typicode/husky#usage
Бажано і pre-commit і pre-push наприклад на запуск eslint

**Comment by dimakrugly** [comment]
Пофікшено в новій гілці) 
Хуки працюють
![Husky](https://user-images.githubusercontent.com/106512918/218447837-e77202f8-ec05-48ea-afd2-acd8c5b2054a.png)

**Comment by dimakrugly** [comment]
commit-msg перевіряє комміт по шаблону-регулярці, 
pre-commit лінтером пробігає по всьому проекту
