### ISSUE TITLE
Залежності

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [dimakrugly/onix#8]
`eslint-config-airbnb` та `eslint-plugin-import` потрібні лише під час розробки тож встановлювати їх потрібно з прапором --save-dev тоді вони встановляться в розділ `devDependencies`

**Comment by dimakrugly** [comment]
Дякую, пофікшено)

"dependencies": {
    "@testing-library/jest-dom": "^5.16.5",
    "@testing-library/react": "^13.4.0",
    "@testing-library/user-event": "^13.5.0",
    "prop-types": "^15.8.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-scripts": "5.0.1",
    "scss": "^0.2.4",
    "web-vitals": "^2.1.4"
  },

 "devDependencies": {
    "commitlint-with-husky": "^1.0.10",
    "css-loader": "^6.7.3",
    "eslint": "^8.33.0",
    "eslint-config-airbnb": "^19.0.4",
    "eslint-plugin-import": "^2.27.5",
    "gh-pages": "^5.0.0",
    "husky": "^8.0.0",
    "react-router": "^6.8.0",
    "react-router-dom": "^6.8.0"
  }
