### ISSUE TITLE
Попередження в консолі браузера

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [dimakrugly/onix#9]
<img width="746" alt="Screenshot 2023-02-12 at 23 23 47" src="https://user-images.githubusercontent.com/59687966/218340876-18153099-d736-4f29-85d3-5f44111c6a32.png">

**Comment by dimakrugly** [comment]
Пофіксив у новій гілці, з'явиться в мейні після мерджу
![Screenshot_1](https://user-images.githubusercontent.com/106512918/218448215-bdfffd5a-33d3-4d2e-b8c0-ddc77e1a2955.png)
